name: VR Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write

jobs:
  Deploy-VR:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Npm Install
        run: npm install
        shell: bash

      - name: Build Project
        run: npm run build
        shell: bash

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
