name: VR Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Deploy-VR:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Npm Install
        run: npm install
        shell: bash

      - name: Build Project
        run: npm run build
        shell: bash
